room_speed = 60
audio_play_sound(mu_house, 1, true)
global.key_left = vk_left
global.key_right = vk_right
global.key_up = vk_up
global.key_down = vk_down
global.key_jump = ord("Z")
global.key_slap = ord("X")
global.key_taunt = ord("C")
global.key_attack = vk_shift
